### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by RocoWayne** [EvolSoft/BackToLastPoint#2]
This plugin how does it work? What can i do with it? Love your plugins!

**Comment by Flavius12** [comment]
This plugin let you return back to the previous point when you die or when you relogin. Documentation is available [Here](http://forums.pocketmine.net/plugins/backtolastpoint.983/field?field=documentation)

**Comment by RocoWayne** [comment]
I test the plugin and i spawn in void, i cant make to the hub.
